=== mezentsev-p/feature-architecture-example/SportsMissions/assets/SportsMissions_config.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/SportsMissionsConfig",
    "definitions": {
        "SportsMissionsConfig": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "SportsMissions_Consts": {
                    "$ref": "#/definitions/SportsMissionsConsts"
                },
                "LocalContextConfig": {
                    "$ref": "#/definitions/LocalContextConfig"
                },
                "ScheduleConfig": {
                    "$ref": "#/definitions/ScheduleConfig"
                },
                "SportsMissionConfig": {
                    "$ref": "#/definitions/SportsMissionConfig"
                },
                "ResourcePackDownloadConfig": {
                    "$ref": "#/definitions/ResourcePackDownloadConfig"
                },
                "ContextRegistratorConfig": {
                    "$ref": "#/definitions/ContextRegistratorConfig"
                },
                "StateMachineConfig": {
                    "$ref": "#/definitions/StateMachineConfig"
                }
            },
            "required": [
                "ContextRegistratorConfig",
                "LocalContextConfig",
                "ResourcePackDownloadConfig",
                "ScheduleConfig",
                "SportsMissionConfig",
                "SportsMissions_Consts",
                "StateMachineConfig"
            ],
            "title": "SportsMissionsConfig"
        },
        "ContextRegistratorConfig": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "globalId": {
                    "type": "string"
                },
                "contextComponentHolder": {
                    "type": "string"
                }
            },
            "required": [
                "contextComponentHolder",
                "globalId"
            ],
            "title": "ContextRegistratorConfig"
        },
        "LocalContextConfig": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "contextName": {
                    "type": "string"
                },
                "variables": {
                    "$ref": "#/definitions/LocalContextConfigVariables"
                }
            },
            "required": [
                "contextName",
                "variables"
            ],
            "title": "LocalContextConfig"
        },
        "LocalContextConfigVariables": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "IsAllPacksDownloaded": {
                    "$ref": "#/definitions/IsAllPacksDownloaded"
                },
                "IsLaunchConditionsSatisfied": {
                    "$ref": "#/definitions/EnableCondition"
                },
                "IsEventActive": {
                    "$ref": "#/definitions/EnableCondition"
                },
                "CurrentState": {
                    "$ref": "#/definitions/CurrentState"
                },
                "IsMinPlayerLevelReached": {
                    "$ref": "#/definitions/EnableCondition"
                },
                "CheckLaunchRequirements": {
                    "$ref": "#/definitions/EnableCondition"
                },
                "WelcomeWindow": {
                    "$ref": "#/definitions/WelcomeWindow"
                }
            },
            "required": [
                "CheckLaunchRequirements",
                "CurrentState",
                "IsAllPacksDownloaded",
                "IsEventActive",
                "IsLaunchConditionsSatisfied",
                "IsMinPlayerLevelReached",
                "WelcomeWindow"
            ],
            "title": "LocalContextConfigVariables"
        },
        "EnableCondition": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "lua": {
                    "type": "string"
                }
            },
            "required": [
                "lua"
            ],
            "title": "EnableCondition"
        },
        "CurrentState": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string"
                },
                "value": {
                    "$ref": "#/definitions/CurrentStateValue"
                }
            },
            "required": [
                "type",
                "value"
            ],
            "title": "CurrentState"
        },
        "CurrentStateValue": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "type": {
                    "type": "string"
                },
                "binding": {
                    "type": "string"
                }
            },
            "required": [
                "binding",
                "type"
            ],
            "title": "CurrentStateValue"
        },
        "IsAllPacksDownloaded": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "value": {
                    "$ref": "#/definitions/IsAllPacksDownloadedValue"
                }
            },
            "required": [
                "value"
            ],
            "title": "IsAllPacksDownloaded"
        },
        "IsAllPacksDownloadedValue": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "binding": {
                    "type": "string"
                }
            },
            "required": [
                "binding"
            ],
            "title": "IsAllPacksDownloadedValue"
        },
        "WelcomeWindow": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "TitleLabelTextID": {
                    "type": "string"
                },
                "StartButtonTextID": {
                    "type": "string"
                }
            },
            "required": [
                "StartButtonTextID",
                "TitleLabelTextID"
            ],
            "title": "WelcomeWindow"
        },
        "ResourcePackDownloadConfig": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "packId": {
                    "type": "string"
                },
                "enableCondition": {
                    "$ref": "#/definitions/EnableCondition"
                },
                "requiredCondition": {
                    "$ref": "#/definitions/EnableCondition"
                }
            },
            "required": [
                "enableCondition",
                "packId",
                "requiredCondition"
            ],
            "title": "ResourcePackDownloadConfig"
        },
        "ScheduleConfig": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "commonEnabledCondition": {
                    "$ref": "#/definitions/EnableCondition"
                },
                "scheduleConfigs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ScheduleConfigElement"
                    }
                },
                "needTryActivateOnActivate": {
                    "type": "boolean"
                },
                "needTryActivateOnUpdate": {
                    "type": "boolean"
                }
            },
            "required": [
                "commonEnabledCondition",
                "needTryActivateOnActivate",
                "needTryActivateOnUpdate",
                "scheduleConfigs"
            ],
            "title": "ScheduleConfig"
        },
        "ScheduleConfigElement": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "cheatLaunch": {
                    "type": "boolean"
                },
                "activateStart": {
                    "type": "integer"
                },
                "activateEnd": {
                    "type": "integer"
                },
                "enabled": {
                    "$ref": "#/definitions/Enabled"
                }
            },
            "required": [
                "activateEnd",
                "activateStart",
                "id",
                "type"
            ],
            "title": "ScheduleConfigElement"
        },
        "Enabled": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "conditionAsset": {
                    "type": "string"
                }
            },
            "required": [
                "conditionAsset"
            ],
            "title": "Enabled"
        },
        "SportsMissionConfig": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "balanceAsset": {
                    "$ref": "#/definitions/BalanceAsset"
                },
                "rewardsBalanceAsset": {
                    "$ref": "#/definitions/BalanceAsset"
                }
            },
            "required": [
                "balanceAsset",
                "rewardsBalanceAsset"
            ],
            "title": "SportsMissionConfig"
        },
        "BalanceAsset": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "assetType": {
                    "type": "string"
                },
                "assetId": {
                    "type": "string"
                }
            },
            "required": [
                "assetId",
                "assetType"
            ],
            "title": "BalanceAsset"
        },
        "SportsMissionsConsts": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "contextName": {
                    "type": "string"
                },
                "variables": {
                    "$ref": "#/definitions/SportsMissionsConstsVariables"
                }
            },
            "required": [
                "contextName",
                "variables"
            ],
            "title": "SportsMissionsConsts"
        },
        "SportsMissionsConstsVariables": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "IS_TUTORIAL_ENABLED": {
                    "type": "boolean"
                },
                "SHOW_TUTORIAL_ON_START": {
                    "type": "boolean"
                },
                "MIN_START_STORY_LEVEL": {
                    "type": "integer"
                }
            },
            "required": [
                "IS_TUTORIAL_ENABLED",
                "MIN_START_STORY_LEVEL",
                "SHOW_TUTORIAL_ON_START"
            ],
            "title": "SportsMissionsConstsVariables"
        },
        "StateMachineConfig": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "defaultState": {
                    "type": "string"
                },
                "states": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/State"
                    }
                },
                "handlersSettings": {
                    "$ref": "#/definitions/HandlersSettings"
                }
            },
            "required": [
                "defaultState",
                "handlersSettings",
                "states"
            ],
            "title": "StateMachineConfig"
        },
        "HandlersSettings": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "InProgress": {
                    "$ref": "#/definitions/InProgress"
                }
            },
            "required": [
                "InProgress"
            ],
            "title": "HandlersSettings"
        },
        "InProgress": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "eventsFilter": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "statesFilter": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "eventsFilter",
                "statesFilter"
            ],
            "title": "InProgress"
        },
        "State": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                },
                "transitions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Transition"
                    }
                }
            },
            "required": [
                "name",
                "transitions"
            ],
            "title": "State"
        },
        "Transition": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "target": {
                    "type": "string"
                },
                "triggerIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "target",
                "triggerIds"
            ],
            "title": "Transition"
        }
    }
}

=== mezentsev-p/feature-architecture-example/SportsMissions/assets/SportsMissions_config.json
{
  "SportsMissions_Consts": {
    "contextName": "SportsMissions_Consts",
    "variables": {
      "IS_TUTORIAL_ENABLED": true,
      "SHOW_TUTORIAL_ON_START": false,
      "MIN_START_STORY_LEVEL": 101
    }
  },
  "LocalContextConfig": {
    "contextName": "SportsMissions_Loader",
    "variables": {
        "IsAllPacksDownloaded": {
          "value": {
            "binding": "@gffResourcePackDownloadComponent:allPackDownloaded"
          }
        },
        "IsLaunchConditionsSatisfied": {
          "lua": "return GetContextValue('IsAllPacksDownloaded') and not GetContextValue('IsEventActive')"
        },
        "IsEventActive": {
          "lua": "return GetPropertyValue('@gffStateMachineComponent:currentState') ~= 'Disabled'"
        },
        "CurrentState": {
          "type": "stringValueVariable",
          "value": {
            "type": "stringValueFromProperty",
            "binding": "@gffStateMachineComponent:currentState"
          }
        },
        "IsMinPlayerLevelReached": {
          "lua": "return GetGlobalValue('CurrMainStoryLevel') >= GetContextValue('MIN_START_STORY_LEVEL')"
        },
        "CheckLaunchRequirements": {
          "lua": "return GetContextValue('IsMinPlayerLevelReached')"
        },
        "WelcomeWindow": {
          "TitleLabelTextID": "SportsMissionsTitleLabel",
          "StartButtonTextID": "SportsMissionsStartButtonLabel"
        }
    }
  },
  "ScheduleConfig": {
    "commonEnabledCondition": {
      "lua": "return GetContextValue('CheckLaunchRequirements') and GetContextValue('IsLaunchConditionsSatisfied')"
    },
    "scheduleConfigs": [
      {
        "id": "SportsMissions_CheatStart",
        "type": "gffTimeRangeScheduleLaunch",
        "cheatLaunch": true,
        "activateStart": 1756018800,
        "activateEnd": 1756364400
      },
      {
        "id": "SportsMissions820s1[TaskPack2]",
        "type": "gffTimeRangeScheduleLaunch",
        "activateStart": 1757314800,
        "activateEnd": 1757660400,
        "enabled": {
          "conditionAsset": "Cond_SportsMissions_LaunchesEnabled"
        }
      }
    ],
    "needTryActivateOnActivate": false,
    "needTryActivateOnUpdate": true
  },
  "SportsMissionConfig": {
    "balanceAsset": {
      "assetType": "SportsMissionsTasksBalanceDataAsset",
      "assetId": "SportsMissions_TaskBalanceDataAsset"
    },
    "rewardsBalanceAsset": {
      "assetType": "SportsMissionsTasksRewardsDataAsset",
      "assetId": "SportsMissions_TaskRewardsDataAsset"
    }
  },
  "ResourcePackDownloadConfig": {
    "packId": "SportsMissions",
    "enableCondition": {
      "lua": "return GetContextValue('IsEventActive')"
    },
    "requiredCondition": {
      "lua": "return GetGlobalValue('CurrMainStoryLevel') >= (GetContextValue('MIN_START_STORY_LEVEL') - 5)"
    }
  },
  "ContextRegistratorConfig": {
    "globalId": "GlobalSportsMissionsLoaderFeature",
    "contextComponentHolder": "SportsMissionsLoaderContext"
  },
  "StateMachineConfig": {
    "defaultState": "Disabled",
    "states": [
      {
        "name": "Disabled",
        "transitions": [
          {
            "target": "WaitStart",
            "triggerIds": ["StateGraph.ToWaitStart"]
          }
        ]
      },
      {
        "name": "WaitStart",
        "transitions": [
          {
            "target": "InProgress",
            "triggerIds": ["StateGraph.ToInProgress"]
          },
          {
            "target": "Disabled",
            "triggerIds": ["StateGraph.ToDisabled"]
          }
        ]
      },
      {
        "name": "InProgress",
        "transitions": [
          {
            "target": "Completed",
            "triggerIds": ["StateGraph.ToCompleted"]
          },
          {
            "target": "TimeoutReward",
            "triggerIds": ["StateGraph.ToTimeoutReward"]
          },
          {
            "target": "Disabled",
            "triggerIds": ["StateGraph.ToDisabled"]
          }
        ]
      },
      {
        "name": "Completed",
        "transitions": [
          {
            "target": "FinalReward",
            "triggerIds": ["StateGraph.ToFinalReward"]
          },
          {
            "target": "Disabled",
            "triggerIds": ["StateGraph.ToDisabled"]
          }
        ]
      },
      {
        "name": "TimeoutReward",
        "transitions": [
          {
            "target": "Disabled",
            "triggerIds": ["StateGraph.ToDisabled"]
          }
        ]
      },
      {
        "name": "FinalReward",
        "transitions": [
          {
            "target": "Disabled",
            "triggerIds": ["StateGraph.ToDisabled"]
          }
        ]
      }
    ],
    "handlersSettings": {
      "InProgress": {
        "eventsFilter": ["EnterComplete"],
        "statesFilter": ["InProgress"]
      }
    }
  }
}
